// Fetches live Sydney events from Ticketmaster and writes them to
// seedData/ticketmasterEvents.ts — a static generated file, same pattern as
// suburbs.ts. Rerun this (e.g. once a day) and reseed to refresh; the demo
// never depends on a live API call happening during judging (handoff doc,
// section 10).

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { suburbs } from "./seedData/suburbs";
import { fetchSydneyEvents, nearestSuburb } from "./ticketmaster";
import type { EventSeed } from "./seedData/events";

const OUTPUT_PATH = path.join(__dirname, "seedData", "ticketmasterEvents.ts");

async function main() {
  const apiKey = process.env.TICKETMASTER_API_KEY;
  if (!apiKey) throw new Error("Missing TICKETMASTER_API_KEY in .env");

  const events = await fetchSydneyEvents(apiKey, (lat, lng) => nearestSuburb(lat, lng, suburbs));
  console.log(`Fetched ${events.length} live events from Ticketmaster.`);

  const body = events
    .map(
      (e: EventSeed) => `  {
    suburbName: ${JSON.stringify(e.suburbName)},
    title: ${JSON.stringify(e.title)},
    category: ${JSON.stringify(e.category)},
    description: ${JSON.stringify(e.description)},
    lat: ${e.lat},
    lng: ${e.lng},
    address: ${JSON.stringify(e.address)},
    energyTag: ${JSON.stringify(e.energyTag)},
    socialTag: ${JSON.stringify(e.socialTag)},
    wheelchairAccessible: ${e.wheelchairAccessible},
    sensoryFriendly: ${e.sensoryFriendly},
    multilingual: ${e.multilingual},
    startTime: ${JSON.stringify(e.startTime)},
    endTime: ${JSON.stringify(e.endTime)},
  },`
    )
    .join("\n");

  const fileContent = `// Generated by scripts/fetchTicketmasterEvents.ts — live events pulled from
// Ticketmaster's Discovery API (real, currently on-sale events, unlike
// Eventbrite's dead public search). Covers concert/festival/cultural only;
// charity/ngo/historical stay hand-curated in events.ts since Ticketmaster
// has no listings for those. Regenerate with:
//   npx tsx scripts/fetchTicketmasterEvents.ts
// Fetched: ${new Date().toISOString()}

import type { EventSeed } from "./events";

export const ticketmasterEvents: EventSeed[] = [
${body}
];
`;

  fs.writeFileSync(OUTPUT_PATH, fileContent);
  console.log(`Wrote ${events.length} events to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
