// Hand-entered golden-path demo dataset — real, well-known Sydney venues and
// addresses, fictional one-off event instances layered on top so the live
// demo never depends on unpredictable real-time data (handoff doc, section
// 10). Swap/extend with real Eventbrite results in scripts/seed.ts once an
// API key is available; this file is the fallback that always works.
//
// `suburbName` must match a `name` in seedData/suburbs.ts exactly — the
// seed script resolves it to a suburb_id after suburbs are inserted.

export interface EventSeed {
  suburbName: string;
  title: string;
  category: "concert" | "festival" | "charity" | "ngo" | "historical" | "cultural";
  description: string;
  lat: number;
  lng: number;
  address: string;
  energyTag: "low" | "medium" | "high";
  socialTag: "solo" | "small_group" | "crowd";
  wheelchairAccessible: boolean;
  sensoryFriendly: boolean;
  multilingual: boolean;
  startTime: string; // ISO with +10:00 offset
  endTime: string;
}

export const events: EventSeed[] = [
  {
    suburbName: "Sydney CBD & The Rocks",
    title: "Sydney Symphony Under the Sails",
    category: "concert",
    description: "An open-air orchestral performance on the Opera House forecourt as the sun sets over the harbour.",
    lat: -33.8568,
    lng: 151.2153,
    address: "Sydney Opera House, Bennelong Point, Sydney NSW 2000",
    energyTag: "high",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T19:30:00+10:00",
    endTime: "2026-08-29T21:30:00+10:00",
  },
  {
    suburbName: "Sydney CBD & The Rocks",
    title: "First Nations Contemporary Voices",
    category: "cultural",
    description: "A rotating exhibition of contemporary First Nations artists, with gallery talks throughout the day.",
    lat: -33.8590,
    lng: 151.2088,
    address: "Museum of Contemporary Art Australia, 140 George St, The Rocks NSW 2000",
    energyTag: "low",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: true,
    multilingual: true,
    startTime: "2026-08-29T10:00:00+10:00",
    endTime: "2026-08-29T17:00:00+10:00",
  },
  {
    suburbName: "Sydney CBD & The Rocks",
    title: "Susannah Place Living History Tour",
    category: "historical",
    description: "A guided walk-through of a row of 1840s terrace houses, restored and preserved as they were lived in.",
    lat: -33.8593,
    lng: 151.2087,
    address: "Susannah Place Museum, 58-64 Gloucester St, The Rocks NSW 2000",
    energyTag: "low",
    socialTag: "small_group",
    wheelchairAccessible: false,
    sensoryFriendly: false,
    multilingual: false,
    startTime: "2026-08-29T11:00:00+10:00",
    endTime: "2026-08-29T15:00:00+10:00",
  },
  {
    suburbName: "Sydney CBD & The Rocks",
    title: "The Rocks Foreshore Markets",
    category: "festival",
    description: "Weekend stalls of local produce, handmade crafts, and street food along the historic foreshore.",
    lat: -33.8597,
    lng: 151.2086,
    address: "George St, The Rocks NSW 2000",
    energyTag: "medium",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T09:00:00+10:00",
    endTime: "2026-08-29T15:00:00+10:00",
  },
  {
    suburbName: "Newtown",
    title: "Enmore Theatre: Local Rock Showcase",
    category: "concert",
    description: "Four up-and-coming Sydney bands share the bill at one of the city's best-loved live venues.",
    lat: -33.9021,
    lng: 151.1755,
    address: "Enmore Theatre, 118-132 Enmore Rd, Newtown NSW 2042",
    energyTag: "high",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: false,
    startTime: "2026-08-29T20:00:00+10:00",
    endTime: "2026-08-29T23:00:00+10:00",
  },
  {
    suburbName: "Newtown",
    title: "Camperdown Memorial Community Bake Sale",
    category: "charity",
    description: "A neighbourhood bake sale raising funds for the local community food pantry.",
    lat: -33.8968,
    lng: 151.1783,
    address: "Camperdown Memorial Rest Park, Australia St, Camperdown NSW 2050",
    energyTag: "low",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: true,
    multilingual: false,
    startTime: "2026-08-29T09:00:00+10:00",
    endTime: "2026-08-29T13:00:00+10:00",
  },
  {
    suburbName: "Marrickville",
    title: "Addi Road Community Pantry — Volunteers Needed",
    category: "ngo",
    description: "Sort and pack rescued groceries for same-day distribution to families across the inner west.",
    lat: -33.9101,
    lng: 151.1631,
    address: "Addison Road Community Organisation, 142 Addison Rd, Marrickville NSW 2204",
    energyTag: "medium",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T09:00:00+10:00",
    endTime: "2026-08-29T12:00:00+10:00",
  },
  {
    suburbName: "Marrickville",
    title: "Sydenham Road Warehouse Sessions",
    category: "concert",
    description: "A late-night set from a local DJ collective inside one of Marrickville's warehouse breweries.",
    lat: -33.9134,
    lng: 151.1502,
    address: "44 Sydenham Rd, Marrickville NSW 2204",
    energyTag: "high",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: false,
    startTime: "2026-08-29T19:00:00+10:00",
    endTime: "2026-08-29T23:00:00+10:00",
  },
  {
    suburbName: "Surry Hills",
    title: "New Australian Voices: Play Reading Night",
    category: "cultural",
    description: "Three unpublished scripts get their first public read-through, with audience feedback after.",
    lat: -33.8827,
    lng: 151.2145,
    address: "Belvoir St Theatre, 25 Belvoir St, Surry Hills NSW 2010",
    energyTag: "low",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: true,
    multilingual: false,
    startTime: "2026-08-29T18:30:00+10:00",
    endTime: "2026-08-29T20:30:00+10:00",
  },
  {
    suburbName: "Surry Hills",
    title: "Prince Alfred Park Community Fair",
    category: "festival",
    description: "Local makers, food trucks, and a kids' zone fill the park for a Saturday community fair.",
    lat: -33.8842,
    lng: 151.2093,
    address: "Prince Alfred Park, Chalmers St, Surry Hills NSW 2010",
    energyTag: "medium",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T10:00:00+10:00",
    endTime: "2026-08-29T16:00:00+10:00",
  },
  {
    suburbName: "Bondi Beach",
    title: "Bondi Pavilion Charity Ocean Swim",
    category: "charity",
    description: "A timed open-water swim along Bondi Beach raising funds for coastal conservation.",
    lat: -33.8912,
    lng: 151.2745,
    address: "Bondi Pavilion, Queen Elizabeth Dr, Bondi Beach NSW 2026",
    energyTag: "high",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: false,
    startTime: "2026-08-29T07:00:00+10:00",
    endTime: "2026-08-29T10:00:00+10:00",
  },
  {
    suburbName: "Bondi Beach",
    title: "Bondi to Coogee Coastal Art Walk",
    category: "cultural",
    description: "A self-guided walk along the coastal path, tracing outdoor sculpture and street art installations.",
    lat: -33.8930,
    lng: 151.2760,
    address: "Notts Ave, Bondi Beach NSW 2026",
    energyTag: "medium",
    socialTag: "small_group",
    wheelchairAccessible: false,
    sensoryFriendly: true,
    multilingual: false,
    startTime: "2026-08-29T08:00:00+10:00",
    endTime: "2026-08-29T12:00:00+10:00",
  },
  {
    suburbName: "Manly",
    title: "Manly Art Gallery: Then & Now Photography",
    category: "historical",
    description: "Archival photographs of Manly's beachfront paired with present-day shots taken from the same spots.",
    lat: -33.7975,
    lng: 151.2872,
    address: "Manly Art Gallery & Museum, West Esplanade, Manly NSW 2095",
    energyTag: "low",
    socialTag: "solo",
    wheelchairAccessible: true,
    sensoryFriendly: true,
    multilingual: false,
    startTime: "2026-08-29T10:00:00+10:00",
    endTime: "2026-08-29T16:00:00+10:00",
  },
  {
    suburbName: "Manly",
    title: "The Corso Sunset Market",
    category: "festival",
    description: "Evening stalls and street performers line Manly's pedestrian mall as the beach empties out.",
    lat: -33.7975,
    lng: 151.2853,
    address: "The Corso, Manly NSW 2095",
    energyTag: "medium",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T15:00:00+10:00",
    endTime: "2026-08-29T19:00:00+10:00",
  },
  {
    suburbName: "Glebe",
    title: "Glebe Markets",
    category: "festival",
    description: "A Saturday institution — vintage clothing, records, and food stalls in the primary school grounds.",
    lat: -33.8809,
    lng: 151.1868,
    address: "Glebe Public School, cnr Glebe Point Rd & Derby Pl, Glebe NSW 2037",
    energyTag: "medium",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: false,
    startTime: "2026-08-29T10:00:00+10:00",
    endTime: "2026-08-29T16:00:00+10:00",
  },
  {
    suburbName: "Glebe",
    title: "Glebe Foreshore Walk Charity Fundraiser",
    category: "charity",
    description: "A sponsored morning walk around Jubilee Park and the Bay Run, raising funds for a local shelter.",
    lat: -33.8687,
    lng: 151.1836,
    address: "Jubilee Park, Glebe NSW 2037",
    energyTag: "medium",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: true,
    multilingual: false,
    startTime: "2026-08-29T08:00:00+10:00",
    endTime: "2026-08-29T11:00:00+10:00",
  },
  {
    suburbName: "Redfern & Eveleigh",
    title: "Carriageworks: Sydney Contemporary Preview Night",
    category: "cultural",
    description: "First look at a rotating contemporary art fair inside the old rail workshops, with artist talks.",
    lat: -33.8927,
    lng: 151.1967,
    address: "Carriageworks, 245 Wilson St, Eveleigh NSW 2015",
    energyTag: "medium",
    socialTag: "crowd",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T18:00:00+10:00",
    endTime: "2026-08-29T22:00:00+10:00",
  },
  {
    suburbName: "Redfern & Eveleigh",
    title: "Redfern Community Op-Shop Volunteer Morning",
    category: "ngo",
    description: "Sort donated clothing and household goods ahead of the weekend op-shop opening.",
    lat: -33.8918,
    lng: 151.2039,
    address: "Redfern Community Centre, 29-53 Hugo St, Redfern NSW 2016",
    energyTag: "low",
    socialTag: "small_group",
    wheelchairAccessible: true,
    sensoryFriendly: false,
    multilingual: true,
    startTime: "2026-08-29T09:00:00+10:00",
    endTime: "2026-08-29T12:00:00+10:00",
  },
];
